version: 0.0
os: linux
files:
  - source: /
    destination: /ec2-user/home/xsj-ui-starter-app
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
