version: 0.0
os: linux
files:
  - source: /
    destination: /ec2-user/home/versus/versus-ui-starter-app
hooks:
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
